# Generated by Django 5.0 on 2023-12-27 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='STORE.collection')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
