# Generated by Django 5.0 on 2023-12-27 21:08

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    Product = apps.get_model("STORE", "Product")
    for row in Product.objects.all():
        row.uuid_id = uuid.uuid4()
        row.save(update_fields=["uuid_id"])

class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0002_product_uuid_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
