# Generated by Django 5.0 on 2023-12-27 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0003_auto_20231227_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
