# Generated by Django 5.0 on 2023-12-28 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0009_cart_cartitem'),
    ]

    operations = [
    ]
