# Generated by Django 5.0 on 2023-12-28 23:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0015_auto_20231228_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
