# Generated by Django 5.0 on 2023-12-28 23:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0016_auto_20231228_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
