# Generated by Django 5.0 on 2023-12-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0017_remove_cart_id_remove_cartitem_id_alter_cart_uuid_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uuid_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='uuid_id',
            new_name='id',
        ),
    ]
