# Generated by Django 5.0 on 2023-12-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0018_rename_uuid_id_cart_id_rename_uuid_id_cartitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
