# Generated by Django 5.0 on 2023-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0019_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
