# Generated by Django 5.2.5 on 2025-08-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0023_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
