# Generated by Django 5.0 on 2023-12-29 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFILE', '0002_alter_user_managers_user_max_otp_try_user_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_otp_try',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_max_out',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=100, unique=True, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
    ]
