# Generated by Django 5.0 on 2023-12-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFILE', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
