# Generated by Django 5.0 on 2024-01-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PROFILE", "0006_alter_user_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_otp_verified",
        ),
        migrations.AddField(
            model_name="user",
            name="reset_timer",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
