# Generated by Django 5.0 on 2024-02-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PROFILE", "0007_remove_user_email_otp_verified_user_reset_timer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
