# Generated by Django 5.2.5 on 2025-08-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFILE', '0010_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
