# Generated by Django 5.2.5 on 2025-08-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROFILE', '0012_user_last_otp_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_link_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
